# Generated by Django 4.0.6 on 2022-09-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mlModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('architecture', models.FileField(upload_to='')),
                ('weights', models.FileField(upload_to='')),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
